#!/usr/bin/env python3
"""Generate native marketplace manifests from the Claude marketplace source.

The Claude marketplace remains the metadata source of truth. This script keeps
the Codex, Grok, and Cursor catalogs synchronized and creates Agent Skill
wrappers when a command has no native skill, which lets Codex load new
command-based plugins without a bridge.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[1]
CLAUDE_MARKETPLACE = ROOT / ".claude-plugin" / "marketplace.json"
REPOSITORY_URL = "https://github.com/omriariav/omri-marketplace"
DISPLAY_NAME_OVERRIDES = {
    "copy": "Copy",
    "setup-pulse": "Setup Pulse",
    "x": "X",
    "skill-reviewer": "Skill Reviewer",
    "find-session": "Find Session",
    "gdoc-math": "Google Docs Math",
    "claude-reviewer": "Claude Reviewer",
    "coacher": "Coacher",
    "natbag": "Natbag",
}

DEFAULT_PROMPT_OVERRIDES = {
    "copy": "Copy the latest table for Slack.",
    "setup-pulse": "Set up the Claude Pulse statusline.",
    "x": "Read this X post and summarize it.",
    "skill-reviewer": "Review this skill against the quality rubric.",
    "find-session": "Find my recent session about this topic.",
    "gdoc-math": "Turn this Markdown with equations into a Google Doc.",
    "claude-reviewer": "Audit this project's Claude configuration.",
    "coacher": "Activate the peer-collaborator coaching frame.",
    "natbag": "Show today's departures from Ben Gurion Airport.",
}

SHORT_DESCRIPTION_OVERRIDES = {
    "copy": "Format and copy output for Slack, email, Google Docs, Jira, Markdown, or rich text.",
    "setup-pulse": "Install the Claude Pulse token-usage statusline.",
    "x": "Read and post X messages from an AI-agent workflow.",
    "skill-reviewer": "Review an Agent Skill against a practical quality rubric.",
    "find-session": "Find and resume past Claude Code or Codex sessions.",
    "gdoc-math": "Create Google Docs with native editable equations from Markdown and LaTeX.",
    "claude-reviewer": "Audit a project's Claude Code configuration against best practices.",
    "coacher": "Activate a direct peer-collaborator frame for AI coding agents.",
    "natbag": "Query live and historical Ben Gurion Airport flight data.",
}

GENERATED_MARKER = "<!-- Generated by scripts/sync-native-manifests.py. -->"


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="Report generated files that are missing or stale without writing them.",
    )
    parser.add_argument("--root", type=Path, default=ROOT, help=argparse.SUPPRESS)
    return parser.parse_args()


def load_json(path: Path) -> dict[str, Any]:
    payload = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(payload, dict):
        raise ValueError(f"{path} must contain a JSON object")
    return payload


def json_text(payload: dict[str, Any]) -> str:
    return json.dumps(payload, indent=2, ensure_ascii=False) + "\n"


def sync_file(path: Path, contents: str, *, check: bool, stale: list[Path]) -> None:
    if check:
        if not path.is_file() or path.read_text(encoding="utf-8") != contents:
            stale.append(path.relative_to(ROOT))
        return
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(contents, encoding="utf-8")


def sync_cursor_hook_override(
    path: Path, empty_hooks: str, *, check: bool, stale: list[Path]
) -> None:
    if path.is_file():
        existing = load_json(path)
        hooks = existing.get("hooks")
        if not isinstance(hooks, dict):
            raise ValueError(f"{path} must contain a hooks object")
        if hooks:
            # A non-empty file is a deliberate Cursor-native translation.
            return
    sync_file(path, empty_hooks, check=check, stale=stale)


def manifest_metadata(source: dict[str, Any]) -> dict[str, Any]:
    allowed = (
        "name",
        "version",
        "description",
        "author",
        "homepage",
        "repository",
        "license",
        "keywords",
    )
    return {key: source[key] for key in allowed if key in source}


def neutral_description(description: str) -> str:
    return description.replace("Claude output", "AI-assistant output").replace(
        "from Claude Code", "from an AI-agent workflow"
    )


def display_name(plugin_name: str) -> str:
    return DISPLAY_NAME_OVERRIDES.get(
        plugin_name, plugin_name.replace("-", " ").title()
    )


def category_name(raw_category: str) -> str:
    return raw_category.replace("-", " ").title()


def short_description(plugin_name: str, description: str) -> str:
    override = SHORT_DESCRIPTION_OVERRIDES.get(plugin_name)
    if override is not None:
        return override
    first_sentence = description.split(". ", 1)[0].rstrip(".") + "."
    if len(first_sentence) <= 120:
        return first_sentence
    shortened = first_sentence[:117].rsplit(" ", 1)[0].rstrip(".,;:")
    return shortened + "…"


def default_prompt(plugin_name: str) -> str:
    return DEFAULT_PROMPT_OVERRIDES.get(
        plugin_name, f"Use {display_name(plugin_name)} for this task."
    )


def command_skill_name(plugin_name: str, command_name: str) -> str:
    prefix = f"{plugin_name}-"
    return command_name if command_name.startswith(prefix) else prefix + command_name


def command_skill_text(plugin_name: str, command_path: Path) -> str:
    contents = command_path.read_text(encoding="utf-8")
    if not contents.startswith("---\n"):
        raise ValueError(f"{command_path} is missing YAML frontmatter")
    _, frontmatter, body = contents.split("---", 2)
    fields: dict[str, str] = {}
    for line in frontmatter.splitlines():
        if ":" not in line:
            continue
        key, value = line.split(":", 1)
        fields[key.strip()] = value.strip()
    command_name = command_path.stem
    skill_name = command_skill_name(plugin_name, command_name)
    description = fields.get(
        "description", f"Run the {command_name} command for {display_name(plugin_name)}."
    )
    if description in (">", "|"):
        description = f"Run the {command_name} command for {display_name(plugin_name)}."
    argument_hint = fields.get("argument-hint", "[arguments]")
    body = body.replace("${CLAUDE_PLUGIN_ROOT}/", "../../")
    header = (
        "---\n"
        f"name: {skill_name}\n"
        f"description: {json.dumps(neutral_description(description))}\n"
        f"argument-hint: {json.dumps(argument_hint.strip(chr(34) + chr(39)))}\n"
        "---\n\n"
        f"{GENERATED_MARKER}\n\n"
        f"# {display_name(plugin_name)}: {command_name}\n\n"
        "This is the native Agent Skill form of the matching plugin command. "
        "Use the user's request as `$ARGUMENTS`; when no explicit content is given, "
        "select the most recent relevant output from the conversation.\n\n"
    )
    return header + body.lstrip()


def codex_manifest(
    plugin: dict[str, Any],
    source: dict[str, Any],
    plugin_root: Path,
    *,
    has_generated_skills: bool = False,
) -> dict[str, Any]:
    name = source["name"]
    description = neutral_description(source["description"])
    category = category_name(plugin.get("category", "utilities"))
    has_skills = (plugin_root / "skills").is_dir() or has_generated_skills
    has_mcp = (plugin_root / ".mcp.json").is_file()
    has_apps = (plugin_root / ".app.json").is_file()
    if not any((has_skills, has_mcp, has_apps)):
        raise ValueError(
            f"{name} needs a skill, .mcp.json, or .app.json for native Codex support"
        )
    capabilities = [
        label
        for enabled, label in (
            (has_skills, "Skills"),
            (has_mcp, "MCP Servers"),
            (has_apps, "Apps"),
        )
        if enabled
    ]
    components: dict[str, Any] = {}
    if has_skills:
        components["skills"] = "./skills/"
    if has_mcp:
        components["mcpServers"] = "./.mcp.json"
    if has_apps:
        components["apps"] = "./.app.json"
    payload = {
        "name": name,
        "version": source["version"],
        "description": description,
        "author": source["author"],
        "homepage": source.get("homepage", f"{REPOSITORY_URL}/tree/main/plugins/{name}"),
        "repository": source.get("repository", REPOSITORY_URL),
        **({"license": source["license"]} if "license" in source else {}),
        **({"keywords": plugin["keywords"]} if "keywords" in plugin else {}),
        **components,
        "interface": {
            "displayName": display_name(name),
            "shortDescription": short_description(name, description),
            "longDescription": description,
            "developerName": "Omri Ariav",
            "category": category,
            "capabilities": capabilities,
            "websiteURL": f"{REPOSITORY_URL}/tree/main/plugins/{name}",
            "defaultPrompt": [default_prompt(name)],
            "brandColor": "#111827",
        },
    }
    return payload


def cursor_manifest(source: dict[str, Any], plugin_root: Path) -> dict[str, Any]:
    payload = manifest_metadata(source)
    payload["description"] = neutral_description(payload["description"])
    if (plugin_root / "skills").is_dir():
        payload["skills"] = "./skills/"
    if (plugin_root / ".mcp.json").is_file():
        payload["mcpServers"] = "./.mcp.json"
    command_paths = sorted((plugin_root / "commands").glob("*.md"))
    commands_are_portable = all(
        "CLAUDE_PLUGIN_ROOT" not in path.read_text(encoding="utf-8")
        for path in command_paths
    )
    if command_paths and commands_are_portable:
        payload["commands"] = "./commands/"
    if source["name"] == "coacher":
        payload["rules"] = "./.cursor-plugin/rules/"
        payload["hooks"] = "./.cursor-plugin/hooks.json"
    elif (plugin_root / "hooks" / "hooks.json").is_file():
        # Claude/Grok hook payloads use different event names and nesting. The
        # skill remains functional; an explicit empty hook file prevents
        # Cursor's default discovery from parsing the foreign format.
        payload["hooks"] = "./.cursor-plugin/hooks.json"
    return payload


def grok_manifest(source: dict[str, Any]) -> dict[str, Any]:
    payload = manifest_metadata(source)
    payload["description"] = neutral_description(payload["description"])
    return payload


def validate_source_manifest(name: str, source: dict[str, Any]) -> None:
    for field in ("name", "version", "description"):
        value = source.get(field)
        if not isinstance(value, str) or not value.strip():
            raise ValueError(f"{name}: Claude manifest field {field!r} is required")
    author = source.get("author")
    if not isinstance(author, dict) or not isinstance(author.get("name"), str):
        raise ValueError(f"{name}: Claude manifest author.name is required")


def marketplace_entry_metadata(
    plugin: dict[str, Any], source: dict[str, Any]
) -> tuple[str, dict[str, Any], list[str] | None]:
    description = plugin.get("description", source["description"])
    if not isinstance(description, str) or not description.strip():
        raise ValueError(f"{source['name']}: marketplace description must be a string")
    author = plugin.get("author", source["author"])
    if not isinstance(author, dict) or not isinstance(author.get("name"), str):
        raise ValueError(f"{source['name']}: marketplace author.name must be a string")
    keywords = plugin.get("keywords", source.get("keywords"))
    if keywords is not None and (
        not isinstance(keywords, list)
        or not all(isinstance(keyword, str) for keyword in keywords)
    ):
        raise ValueError(f"{source['name']}: marketplace keywords must be strings")
    return description, author, keywords


def main() -> int:
    global ROOT, CLAUDE_MARKETPLACE
    args = parse_args()
    ROOT = args.root.resolve()
    CLAUDE_MARKETPLACE = ROOT / ".claude-plugin" / "marketplace.json"
    marketplace = load_json(CLAUDE_MARKETPLACE)
    plugins = marketplace.get("plugins")
    if not isinstance(plugins, list):
        raise ValueError(f"{CLAUDE_MARKETPLACE} must contain a plugins array")

    stale: list[Path] = []

    empty_cursor_hooks = json_text({"hooks": {}})

    codex_entries: list[dict[str, Any]] = []
    cursor_entries: list[dict[str, Any]] = []
    grok_entries: list[dict[str, Any]] = []
    expected_generated_skills: set[Path] = set()

    for plugin in plugins:
        if not isinstance(plugin, dict) or not isinstance(plugin.get("name"), str):
            raise ValueError("every marketplace plugin entry must have a name")
        name = plugin["name"]
        expected_source = f"./plugins/{name}"
        if plugin.get("source") != expected_source:
            raise ValueError(
                f"{name}: native generation requires vendored source {expected_source!r}"
            )
        plugin_root = ROOT / "plugins" / name
        source = load_json(plugin_root / ".claude-plugin" / "plugin.json")
        validate_source_manifest(name, source)
        if source.get("name") != name:
            raise ValueError(f"Claude manifest name mismatch for {name}")
        entry_description, entry_author, entry_keywords = marketplace_entry_metadata(
            plugin, source
        )

        if name == "coacher":
            frame = (plugin_root / "frame.md").read_text(encoding="utf-8")
            cursor_rule = (
                "---\n"
                "description: Maintain the coacher peer-collaborator stance.\n"
                "alwaysApply: true\n"
                "---\n\n"
                + frame
            )
            sync_file(
                plugin_root / ".cursor-plugin" / "rules" / "coacher.mdc",
                cursor_rule,
                check=args.check,
                stale=stale,
            )

        # Codex is skill-first. If a command does not already point at a skill,
        # create a deterministic wrapper. An umbrella skills/<plugin>/SKILL.md
        # signals that the plugin intentionally handles all commands itself.
        commands_root = plugin_root / "commands"
        skills_root = plugin_root / "skills"
        umbrella_skill = skills_root / name / "SKILL.md"
        plugin_has_generated_skills = False
        if commands_root.is_dir() and not umbrella_skill.is_file():
            for command_path in sorted(commands_root.glob("*.md")):
                if (skills_root / command_path.stem / "SKILL.md").is_file():
                    continue
                generated_skill = (
                    skills_root
                    / command_skill_name(name, command_path.stem)
                    / "SKILL.md"
                )
                expected_generated_skills.add(generated_skill)
                plugin_has_generated_skills = True
                sync_file(
                    generated_skill,
                    command_skill_text(name, command_path),
                    check=args.check,
                    stale=stale,
                )

        codex = codex_manifest(
            plugin,
            source,
            plugin_root,
            has_generated_skills=plugin_has_generated_skills,
        )
        cursor = cursor_manifest(source, plugin_root)
        grok = grok_manifest(source)
        if cursor.get("hooks") == "./.cursor-plugin/hooks.json":
            sync_cursor_hook_override(
                plugin_root / ".cursor-plugin" / "hooks.json",
                empty_cursor_hooks,
                check=args.check,
                stale=stale,
            )
        sync_file(
            plugin_root / ".codex-plugin" / "plugin.json",
            json_text(codex),
            check=args.check,
            stale=stale,
        )
        sync_file(
            plugin_root / ".cursor-plugin" / "plugin.json",
            json_text(cursor),
            check=args.check,
            stale=stale,
        )
        sync_file(
            plugin_root / ".grok-plugin" / "plugin.json",
            json_text(grok),
            check=args.check,
            stale=stale,
        )

        category = category_name(plugin.get("category", "utilities"))
        codex_entries.append(
            {
                "name": name,
                "source": {"source": "local", "path": f"./plugins/{name}"},
                "policy": {
                    "installation": "AVAILABLE",
                    "authentication": "ON_INSTALL",
                },
                "category": category,
            }
        )
        cursor_entries.append(
            {
                "name": name,
                "source": f"plugins/{name}",
                "description": neutral_description(entry_description),
                "version": source["version"],
                "author": entry_author,
                "category": category,
                **({"keywords": entry_keywords} if entry_keywords is not None else {}),
            }
        )
        grok_entry = dict(plugin)
        grok_entry["description"] = neutral_description(entry_description)
        grok_entry["author"] = entry_author
        if entry_keywords is not None:
            grok_entry["keywords"] = entry_keywords
        grok_entries.append(grok_entry)

    # Remove only wrappers owned by this generator when their source command is
    # removed or replaced by a hand-authored skill.
    for skill_path in ROOT.glob("plugins/*/skills/*/SKILL.md"):
        if skill_path in expected_generated_skills:
            continue
        try:
            generated = GENERATED_MARKER in skill_path.read_text(encoding="utf-8")
        except OSError:
            generated = False
        if not generated:
            continue
        if args.check:
            stale.append(skill_path.relative_to(ROOT))
        else:
            skill_path.unlink()
            try:
                skill_path.parent.rmdir()
            except OSError:
                pass

    codex_marketplace = {
        "name": marketplace["name"],
        "interface": {"displayName": "Omri's AI Agent Marketplace"},
        "plugins": codex_entries,
    }
    cursor_marketplace = {
        "name": marketplace["name"],
        "owner": marketplace["owner"],
        "metadata": {
            "description": "Personal plugins, skills, commands, and utilities for Cursor."
        },
        "plugins": cursor_entries,
    }
    grok_marketplace = {
        "name": marketplace["name"],
        "owner": marketplace["owner"],
        "metadata": {
            "description": "Personal plugins, skills, commands, and utilities for Grok."
        },
        "plugins": grok_entries,
    }
    sync_file(
        ROOT / ".agents" / "plugins" / "marketplace.json",
        json_text(codex_marketplace),
        check=args.check,
        stale=stale,
    )
    sync_file(
        ROOT / ".cursor-plugin" / "marketplace.json",
        json_text(cursor_marketplace),
        check=args.check,
        stale=stale,
    )
    sync_file(
        ROOT / ".grok-plugin" / "marketplace.json",
        json_text(grok_marketplace),
        check=args.check,
        stale=stale,
    )

    root_source = load_json(ROOT / ".claude-plugin" / "plugin.json")
    root_grok = manifest_metadata(root_source)
    sync_file(
        ROOT / ".grok-plugin" / "plugin.json",
        json_text(root_grok),
        check=args.check,
        stale=stale,
    )

    if stale:
        print("Native manifests are out of sync:", file=sys.stderr)
        for path in stale:
            print(f"- {path}", file=sys.stderr)
        return 1
    if args.check:
        print("Native manifests are in sync.")
    else:
        print("Native manifests synchronized.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
